### PR TITLE
[2/2] Egistec HAL implementation

### PR DESCRIPTION
**Pull request by MarijnS95**
Depends on https://github.com/sonyxperiadev/kernel/pull/1857.

This is a complete C++ implementation driving the Egistec fingerprint sensor and it's accompanying TrustZone application for the Nile platform.
It is complete with switching code that instantiates the right HAL implementation based on the sensor (FPC or ET) detected by the kernel driver.

Note that there is still a lot of verbose debugging info. We can leave this for a while until the HAL is deemed stable enough.

Future improvements include collecting and labeling return (error)codes, plus other minor refactors described in some commits.

### CODE REVIEW

**Comment by jerpelea** [comment]
commit messages please!

**Comment by oshmoun** [comment]
no issues noticed on tama and its fpc sensor

**Comment by jerpelea** [comment]
the finger is still not recognized

**Comment by dimitar10** [comment]
The build fails with:

```external/libcxx/include/algorithm:714: error: undefined reference to 'EGISAPTrustlet::API::RequestOffset'
external/libcxx/include/algorithm:714: error: undefined reference to 'EGISAPTrustlet::API::ResponseOffset'
external/libcxx/include/algorithm:714: error: undefined reference to 'EGISAPTrustlet::API::RequestOffset'
external/libcxx/include/algorithm:714: error: undefined reference to 'EGISAPTrustlet::API::ResponseOffset'
```
A quick and dirty replace of the ResponseOffset and RequestOffset fields in `EGISAPTrustlet.h` with their hex values removes this error, but still the finger is not detected at all. 

On a side note, detection of Egistec vs. FPC  sensors appears to be working. I will provide more feedback in the following days...

**Comment by jerpelea** [comment]
@dimitar10 
stop fps_hal
start fps_hal

**Comment by MarijnS95** [comment]
@dimitar10 It is unfortunately a known issue (2 others with Nile Egistec devices have confirmed), and something I can't reproduce. Well, I can reproduce it, but fixed it on my side with https://github.com/sonyxperiadev/kernel/pull/1863/commits/132453889ffb226a55eed946dd88b39564fbfc1a.
All I can think of is the FPC driver initializing before Egistec, which means the regulator is briefly enabled to check the hardware type.

Would you mind applying this diff and testing again?
```diff
diff --git a/drivers/input/misc/et51x.c b/drivers/input/misc/et51x.c
index 40a765d61af70..55f495a8e0b96 100644
--- a/drivers/input/misc/et51x.c
+++ b/drivers/input/misc/et51x.c
@@ -226,6 +226,7 @@ static int device_prepare(struct et51x_data *et51x, bool enable)
                rc = vreg_setup(et51x, true);
                if (rc)
                        goto exit;
+               hw_reset(et51x);
        } else if (!enable && et51x->prepared) {
                (void)vreg_setup(et51x, false);
        exit:
```
I'm very interested in the logs; on my side any such reset fixes the IRQ issue (as is confirmed by restarting the HAL), though the TZ app requests a hardware reset every time an enroll or authenticate (involving the physical sensor) is initialized.

**Pull request merged**
