### PR TITLE
9.0

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by alviteri** [comment]
ping @MarijnS95

**Comment by alviteri** [comment]
this one 580e400071a76831e670acff89fd866a2444954b is present building inline kernel but i don't know if @jerpelea has error in build with prebuilt kernel if you don't have errors in build like described in comment then i can move that under TARGET_COMPILE_WITH_MSM_KERNEL

**Comment by alviteri** [comment]
the last error remaining is
hardware/sony/fingerprint/fpc_imp.h:31:9: error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]
typedef struct fpc_imp_data_t {
        ^
1 error generated.

**Comment by alviteri** [comment]
this one 580e400 is present building inline kernel but i don't know if @jerpelea has error in build with prebuilt kernel if you don't have errors in build like described in comment then i can move that under TARGET_COMPILE_WITH_MSM_KERNEL

**Comment by alviteri** [comment]
ping @MarijnS95

**Comment by alviteri** [comment]
Ping @humberos

**Comment by alviteri** [comment]
commits updated ....
build done with
make android.hardware.biometrics.fingerprint@2.1-service.sony

 kugo build ok
dora build ok
maple build ok
discovery build ok

**Comment by humberos** [comment]
It's still ok here (suzu).

**Comment by alviteri** [comment]
what about this ? it's confirmed fpc works in P .... can anyone confirm O ? thanks

**Comment by jerpelea** [comment]
cherry-picked

**Pull request merged**
