### PR TITLE
Master rework

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by Myself5** [comment]
The second commit message is more than misleading. Either split up the commit to contain just the spacing and another one to contain the header modifications or reword the commit message.

**Comment by jerpelea** [comment]
2 commits please

**Comment by alviteri** [comment]
done

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/commit/53f9ee48e28e0c7391e444296403eeceeb7d4a31 should remove the separate tone and loire headers(same code in 2 files) and you should unify  the header in the common loire_tone header

**Comment by alviteri** [comment]
done

**Comment by alviteri** [comment]
please test or close .. thanks

**Comment by jerpelea** [comment]
please wait

**Pull request merged**
