### PR TITLE
Egistec: Ganges: don't fail to authenticate if 5 fingerprints are enrolled.

### PR DESCRIPTION
**Pull request by krnlyng**

### CODE REVIEW

**Comment by MarijnS95** [comment]
I fail to see why this is here in the first place. This check should be in `Enroll()` only. If at all, this code should be changed to return an error when there are zero fingers registered.

Let me take a few minutes to figure out where this came from...

**Comment by MarijnS95** [comment]
It is rather weird. This check is only done in the authenticate codepath, and gives off just a warning when no fingers are registered. It doesn't return an error code, probably expecting the actual authentication step to do so?

We should change this to check against zero and return the right error code, and perhaps (as premature measure) move the `>=` to (pre)enroll. Can you make such a change @krnlyng or should I PR that?

**Comment by krnlyng** [comment]
I can do it, what is the correct return value though?

**Comment by MarijnS95** [comment]
I'm not sure, there's nothing really applicable apart `EINVAL`, but that's specific to arguments and not just "this invocation is invalid".
Anyway, the chances for this exception are slim, at least in Android (I don't know about hybris/sailfish) which keeps track of registered prints. Only if that and the db get desynced somehow.

There's no need to move it to `enroll()` btw, `GetNewPrintId` takes care of it already.

**Comment by krnlyng** [comment]
ok i changed it now to check for 0 and return EINVAL as a compromise, i hope that is acceptable.
I am not sure if you meant that the check for >=5 should be in both enroll and preenroll but if it should be in preenroll i'll add it.

**Comment by MarijnS95** [comment]
Looks good like this, thanks for making the change! Since the error code isn't too descriptive, should we add an `ALOGE` in there? We might know what's going on when seeing `authenticate: Have 5 enrolled fingers` but others probably don't.

There should be no check in `preEnroll`. Android calls that to generate a challenge, which is responded to by the user typing in their pin. I bet if we return an error the user won't be able to get to the fingerprint management screen at all. Not to mention deleting one and adding another.

**Comment by krnlyng** [comment]
@MarijnS95 updated the PR.

I still see one issue with fingerprint on ganges though, it's really tricky to enroll the first fingerprint (i.e. WaitForEvent gets stuck and the Finger event is not received no matter how hard i press the sensor), are there any such issues on android too?

It happens only with the first fingerprint, once i've managed to enroll the first one, all others are enrolled without any issue.

**Comment by MarijnS95** [comment]
@krnlyng Thanks!

There's one very small nitpick, where my preference is to not put the word `Error` in a message because that's implied by the `ALOGE`. I would go for `"Unable to %s without enrolled fingerprints!"` but that's just personal styling preference and in no way to be enforced on this project/these files.

I've been chasing the first enrollment issue quite a while back, but ran out of time and forgot about it. As far as I'm aware this is caused by the sensor being turned off after initialization, which stock doesn't do. It seems an enrolled finger keeps the TZ and/or HW alive enough to not fail ever after. This was around the same time the unbalanced `poll_work` issue was resolved, which seemed to fix most of these issues.
There's an ioctl that returns the current GPIO state which I use to debug these cases, and as it seems there is no issue in the kernel nor HAL code; the GPIO remains zero. This means the hardware is simply not set up to register prints, despite returning no errors on any of the calls to get it into enrolling mode.
Restarting the HAL fixes the issue. Redoing some initialization seems to do the trick, and it would be awesome if we can figure out which (could very well be restarting the entire TZ-app, as we know it's riddled with bugs already). I don't have much time left for that now and if you don't either, defining `et51x,enable-on-boot;` in kernel DT could be a temporary workaround for Sailfish.

**Comment by MarijnS95** [comment]
@jerpelea This is acked and **ready to merge**!

**Pull request merged**
