### PR TITLE
Notify unknown fingers

### PR DESCRIPTION
**Pull request by spiiroin**

### CODE REVIEW

**Comment by jerpelea** [comment]
@rayman @bumble-bee

**Comment by Rayman** [comment]
Why am I notified?

**Comment by jerpelea** [comment]
@BuzzBumbleBee

**Comment by jerpelea** [comment]
@EnJens

**Comment by jerpelea** [comment]
@Rayman sorry

**Comment by EnJens** [comment]
@Rayman because my nick everywhere but github is rayman :D

**Comment by EnJens** [comment]
LGTM :+1:

**Pull request merged**
