### PR TITLE
[1/7] Fingerprint gestures!

### PR DESCRIPTION
**Pull request by MarijnS95**
This patchset implements fingerprint gestures, which are used to open/close the QuickSettings/notification panel without having to reach to the top of the screen (and hopefully other cool features in the future).
It adds a lot of complexity to the HAL which is why this should be scrutinized and tested thoroughly. Be sure to read the comment below about state-keeping improvements, and check the commit descriptions for a thorough insight in the thought-process. If that doesn't make it clear yet, I'm not entirely satisfied with the implementation yet. While I do like to keep things as simple and elegant as possible, that also brings a whole hoist of problems on its own (race conditions in this case). I appreciate any and all feedback (after reading the commits of course).

#### Testing

This has been used on Akatsuki for a couple weeks without much issues (apart from coding mistakes which have been amended). No-one has confirmed this to work on Yoshino/Nile yet, so it could be in the same boat as Loire (and probably Tone, see below) which have a blocking call instead of using IRQs. For all I know "newer" platforms _should_ have the better mechanisms, but then Tama is the first one to utilize IRQs on `wait_finger_lost` anyway. Please report your findings!

#### Loire/Tone

These platforms support gestures as well, but with a catch. Tone simply *seems* to crash (I'd like to get this reconfirmed though), and both use a blocking TZ call which holds for as long as a finger is on the sensor. While this doesn't seem as bad as it sounds, blocking in the TZ locks up systemui for as long as a finger is down. Some short stracing shows that the thread responsible for rendering (the one which prints `OpenGLRenderer: Davey! duration=8010ms [...]` after resuming) is waiting in an ioctl to `/dev/kgsl-3d0`...
We could technically enable the feature as long as the user is aware to **not** put and hold their finger on the sensor during normal usage (meaning an ExtendedSettings toggle with double dialog warnings...).
Attempts to alter the configuration related to gestures yields no success thus far. Feel free to help out testing [here](https://github.com/MarijnS95/vendor-sony-oss-fingerprint/tree/loire-tone-swipe-gestures).

#### Improvements

As it seems the eventfd is simply not cutting it anymore. We'll still want to use it to block on events and `/dev/fingerprint` simultaneously, but without taking care of precious state. The most pressing issue being multiple writers incrementing its value before the thread got to it - which is why most of the HAL methods have to _block_ on the thread changing to the desired state before continuing.
Instead, I propose a separate `desired_state` variable which can be safely read without clearing, and written without implicit addition. As you may guess, the advantage here is that we are able to inspect in-flight state - something which is impossible without peeking (_not reading_) the eventfd. Of course these functions are protected by mutexes to prevent unexpected concurrent state changes. The eventfd is switched to a simple binary operation: `0` when nothing is available, anything else when an event is available to wake up ongoing `poll()`s.
Whenever not strictly necessary the HAL doesn't need to wait on the thread to actually change into a state. Instead, future `setState` calls check whether something is in-flight through `desired_state`, and wait for the thread to get there before requesting something different.

#### Formatting

Finally, there's the annoyance of formatting. As you may have noticed all new files contributed by me are autoformatted before committing, but this is annoying to do on existing code. Aside from that, we use different formatting for C and C++: `BreakBeforeBraces: Linux` and K&R respectively (the only difference being braces on a newline for function bodies). We should settle on a sensible default and use it everywhere throughout the project, unless it's possible to have separate `.clang-format` for C and C++.

### CODE REVIEW

**Comment by MarijnS95** [comment]
And that's the first force-push. As it turns out, calling `getAuthenticatorId` during navigation isn't the problem; `fpc_set_auth_challenge` (setup in `authenticate()`) is.
The unnecessary state changes invoked by `clearThread()` and `resumeNavigation()` have been removed.

Furthermore, one of the issues mentioned in the PR has been "patched up": `enroll()` and `authenticate()` do not wait for the thread to switch as this is hardly ever necessary, which causes the mentioned addition on the eventfd when immediately canceled after. This usually happens during boot, where Android quickly requests an authentication session followed by canceling it. Before the thread gets to consume the enroll state (`3`), the cancel state (`5`) has already been written and the eventfd now contains `8` which the thread (luckily) doesn't understand.
For now, this is patched by changing `setState` to `waitForState`. But refactoring the code as mentioned in the PR description sounds like the way to go.

**Comment by kholk** [comment]
Okay, so Loire and Tone shall never get this feature.

If the TZ gets in a blocking wait state, then what kills your Adreno is ... well, the adreno itself:
the GPU firmware does actually communicate through TrustZone because of the support for
secured contexts in the GPU itself (for DRM content, like NetFlix and that kind of stuff).
Even if you're not rendering in a secured context, the calls are still secure, but in this case
the memory region is shared and unsecured (that's the difference between sec and unsec).

So... well, that's a big no: don't tell me that you haven't ever accidentally touched the sensor
with your fingers or your palm while using the device... and if this happens while, for example,
playing a 3d (even not too much intensive) game, the renderer will probably crash due to the
unbearable frameskipping that gets detected (a 2-freakin-second long frameskip means 120
skipped frames on a 60hz machine).

Anyway, since you've put effort in adding the support for also Loire and Tone, then I'm not
telling you to _remove it with fire_... keep it there instead, just never enable it.
Maybe one day someone will find a solution.
Unlikely? Yes.
Impossible? _Maybe_.

**Comment by MarijnS95** [comment]
> don't tell me that you haven't ever accidentally touched the sensor with your fingers or your palm while using the device

@kholk I'm left-handed, of course I'm cheating ;)

As for adding the code, I like the suggestion. The commits have been pushed to this branch and include the required configuration commands to toy with. Unfortunately these consist of only 5 `uint`s that do not make any difference whatsoever.

**Comment by MarijnS95** [comment]
Allright, a lot of new features have just been pushed!

Again, the first few commits are cleanup and preparation, after which all the gesture implementation details follow.

### Synchronization simplification
The cleanup/simplification/stabilization mentioned in the PR description has been implemented. The eventfd is still used to block indefinitely and concurrently on the fingerprint device _and_ events from the control service, but doesn't carry any useful number (due to not being able to peek, and a write doing an increment instead of overwrite).

>     This change implements the new state transition mechanism explained in
>     the PR description here:
>     https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/50
>     
>     The previous system was unable to work correctly with an eventfd that
>     cannot be read without clearing the value, nor safely written without
>     incrementing the previous one.
>     
>     For that reason the desired next state is kept in a separate variable,
>     and any access is protected by a mutex. When a new event is available
>     the eventfd is set to a non-zero value to wake up any pollers. When the
>     worker thread gets to read the next state the eventfd is cleared and the
>     condition variable notified, in case the requester needs to wait for the
>     thread to have finished the current operation.
>     
>     Any "implicit hacks" with non-zero states written to the eventfd are now
>     removed since the eventfd is filled with a non-zero state regardless of
>     what is requested.
>     The cancel state becomes obsolete and is removed as well, since the
>     desired state can now be requested directly.

I feel like this should be amended to some of the commits since that will reduce clutter, but this is unfortunately going to create conflicts with all the other commits. If you have an opinion, please let me know!

### Egistec gestures!
Luckily Ganges and Nile **with the new TZ** support fingerprint gestures just as well. In fact, it is _way_ simpeler with just a _single_ function call, and much, **much** more importantly: _**no crashes when invoking other commands!**_
That means we can keep using the current `WorkerThread` implementation without any extra state synchronization as is the case with FPC.

#### Be sure to flash the latest stock on Nile!
This will update the TZ application to the same version as Ganges, with working gestures.
I will _not_ spend time figuring out how to get it to work on the _now legacy_ Nile TZ app.

### On reusing `WorkerThread`
The initial idea was to move all the state sync into this class, to be able to reuse it. That would have the following advantages:
- Less code duplication, single implementation tested and maintained on all platforms;
- Reuse extended sync for Egistec if it turns out to be necessary for gestures;
- Move thread-related code out of the _already crowded_ `BiometricsFingerprint` HAL.

Unfortunately, this also has a few disadvantages:

- Egistec does not need the extra sync, but has to cope with all the extra kernelspace transitions (syscalls) anyway;
- The most pressing issue: Most of the FPC implementation still lives in C, and it is going to get messy when this needs to access the eventfd/epoll which are then only living within the `WorkerThread` C++ class (without leaking these to a separate struct, not sure who has to `close()` them, that is messy).

**Comment by kholk** [comment]
Why is this still a draft? And why do you still not want this merged?

**Comment by MarijnS95** [comment]
@kholk Exactly because of the outstanding change that I just pushed.

In fact, getting rid of the draft _is_ what I want, as that turns the PR into _**READY FOR REVIEW**_, it even says that.

I just don't want it merged now or tomorrow as a "looks good". It needs proper testing because I have had it lock up my device a few times. That was just bad programming on my side, and is _hopefully_ fixed now but I don't want to take any unnecessary risks.
Especially with the addition of Ganges and new-style Nile, which haven't had _any long-term testing at all_.

Luckily I've been able to recruit some minions to help me out and use this. I've used this on the daily driver since the PR was made, and it's pretty much stable. Of course that doesn't hold true for the changes that were just pushed, as those have been made in the past hour or two.
However, I do not know yet if it works on Nile with FPC nor Yoshino. Maybe those suffer the same consistent lockups or crashes as Loire and Tone, respectively.

**Comment by kholk** [comment]
I agree. Minions, one week of testing is set. After a week, if no issue reported, merge it!

**Comment by MarijnS95** [comment]
@kholk But don't forget:
- Shall I squash the cleanup to reduce bloat (I would say no: Takes too much hassle since it _will_ generate conflicts with the other commits, and it looses a bit of "precious" history showing how it _shouldn't be done_)?
- I would like someone to read through the diff and see if everything makes sense
- `config_supportSystemNavigationKeys` still needs splitting across platform repos because Loire/Tone are borked.

**Comment by kholk** [comment]
1.  Keeping the failure in the history is a way to keep others from repeating your bad mistake (it's not much bloat anyway).

2. I think I can read it tomorrow, but I'm not the best one here to approve strictly userspace related code. If it was kernel stuff, then, you know it'd be a matter of two seconds for me. I can rather approve kernel interactions that you do here though..... 

3. Blacklist whatever seems to not work. If tone and loire have issues, just disable the features there. One day you may find a way, but it'd be a pity not to get these software improvements on Nile, Ganges, Yoshino, Tama and Kumano "just cause". I'm sure that you totally agree with me.

**Comment by jerpelea** [comment]
just disable the missing features for the platforms that dont support them and go for it

**Comment by MarijnS95** [comment]
Of course, point 3. is merely a "note to self" that I should not forget to do. The decision to not put this _as a broken feature_ on Loire/Tone has been made long ago. Obviously we can have the feature on all the other platforms!

And to be completely fair, it is actually part of my day-to-day interaction on Akatsuki, perhaps to a point where using the phone without it is going to be annoying to say the least.
In the beginning I misliked the sensor being relatively low (towards the center) of the body rather than higher up like on Nile. However, when holding the phone one-handed near the bottom where you can easily type with a thumb, swiping the sensor to pull down the quicksettings - read a notification - and swipe it back up again is just _that much more convenient_ compared to reaching to the top to pull it down (which usually requires changing grip). In fact I even use it when getting to media controls in a notification, or to reach the quicksettings themselves :D

There, that's just something for those "disliking" this feature for just being "a gimmick" :grin:

**Comment by Haxk20** [comment]
Seems OK so far on Mermaid. Sometimes the sensor took a few seconds more to recognize the fingerprint when the screen was locked or i had to even tap it again and then it unlocked but that could have been just the oil on the sensor. While using it during the day it worked just fine without an issue.
But to be clear the sensor took more likely because i unlocked it. Locked it. unlocked in and so on for few times in small amount of time.

**Comment by MarijnS95** [comment]
Well I just thought again, and decided to go with a separate `WorkerThread` implementation (which was the initial plan) as I really wanted to pull thread handling out of the already crowded `BiometricsFingerprint`. The simple solution is to _not_ reuse the Egistec `WorkerThread` but instead implement a separate one _without epoll_, resolving the issues mentioned above.

If we ever decide Egistec requires a similar threading mechanism, we can simply add the `epoll_fd` together with `waitForEvent` on top in a derived class.

Unfortunately I have found a rather serious/annoying bug that has apparently been there since the initial version. Tama is known to fail `fpc_auth_step` sometimes, but with the gestures enabled it doesn't recover at all.
This is _partially_ due to a [bug introduced by me a while ago](https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/commit/9b250b6c1e14ed6799e85930a93715059704bfea), closing the fingerprint device _before_ calling `fpc_set_power(0)`. This prevents some cleanup from happening but doesn't interfere in any other way.
After pretty much a day of useless digging I can't find anything. For now, we will let the HAL die in this odd case as that helps it recover (sometimes after one restart, sometimes multiple).
That said, it is important to mention that I didn't notice this _at all over the past few months_. It is hard to reproduce by providing wrong/partial fingerprints in quick succession until the TZ succumbs.
There is a high possibility this is an issue in qseecom (library or kernel driver, perhaps). After all, the initial error is returned from the qseecom function itself, not the TZ response field that is normally used to convey status status codes.

**Comment by kholk** [comment]
The TZ does not accept your command if the device cannot be retrieved when it's completely down or when the TZ decides that you're not allowed to send commands to the specific tzapp that you're targeting.
Usually, you're not allowed to do that when the tzapp generates too many errors (flooding too much) or when it crashed and the tzos decided to kill it. 
In this case you see a qseecom error and not an error reply from TZ (not in all cases, of course).

**Comment by MarijnS95** [comment]
In this case I assume it is either qseecomd passing the wrong arguments, something broken in the kernel or (most likely) the tzos rejecting the call, with `EINVAL`:
`E QSEECOMAPI: Error::send modified command ioctl failed wtih ret = -1, errno = 22`

If it is the tzos there's not much we can do apart very carefully examining whether this happens on Stock, and if they use the tzapp and/or tzos in a slightly different way.

Anyway, the repro steps have become quite clear. Simply hold the wrong finger until you get an authentication denied, then hold any finger again and it'll crash. Sounds like we need to do some cleanup here. That should be easy to find down on stock.

**Comment by MarijnS95** [comment]
And another force-push. I have not yet investigated the unknown-print crash, but the HAL should now be stabler on Nile/Ganges by using the synchronized worker thread there as well.
As it turns out our assumptions about the Android system calling functions and waiting for callbacks is wrong, triggering the "addition on write" issue on the eventfd just as described in the PR description. For that reason I decided to just drop that "simplified" and "efficient" (yet wrong if we cannot guarantee what is called on the interface) implementation, and replace it with the synchronized worker written for extended state handling with FPC gestures.
I have to say we are still much leaner than the stock implementations, that absolutely litter mutexes and condition variables everywhere.

**Comment by MarijnS95** [comment]
@kholk The ugly crash has finally been identified and fixed. I have partially been down this code-path before, but changed too many things and made a little error, thus not seeing it immediately.
As it turns out, the TZ _really_ wants us to call `update_template` (and perhaps the followup `store_user_db`) even when the print id is zero - meaning no match found.

Now I have no idea if this affects Yoshino or FPC-Nile, and thus do not want to make an `#ifdef tama` right away. I don't own these devices, so I request any reader with one of these to try it out and report (with logs!) whether it works or not. Their base implementations share the exact same code flow (both platforms have the extra `has_changed` field in `update_template`, and call these functions regardless of `print_id > 0`) so I only expect improvements :grimacing:.
In fact, I would love if you could test the TZ flood on Yoshino @kholk, perhaps we can remove [this hack](https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/commit/2e9cc28cc0175aa2a4abd35bff404655a2d595b0) again. For now I have inserted a `sleep(1)` in there, which addresses the recovery on Tama (but is of course not needed anymore, now that the issue itself has been fixed and we should not have any of these severe crashes anymore).
This code is anyway shared with Loire (and Tone - not tested), where it works fine. Even retrieving the authentication challenge after updating/storing the DB works fine (of course, also on Tama :wink:).

**Pull request merged**
