### PR TITLE
Update FPC To New Style HAL

### PR DESCRIPTION
**Pull request by BuzzBumbleBee**

### CODE REVIEW

**Comment by jerpelea** [comment]
tests?

**Comment by BuzzBumbleBee** [comment]
@jerpelea I have tested on both tone and yoshino. Needs more testing and comments here before merge

**Comment by jerpelea** [comment]
it needs proper testing on all boards

**Comment by russel5** [comment]
Build it for lilac no fingerprint's menu in settings.
May be need some diff blobs? not v11?
Logs -- https://drive.google.com/open?id=14LknpOX6D_QaIjfOC30OYZfKoGg0VixZ

**Comment by oshmoun** [comment]
seems to work fine after the latest commit, been testing since yesterday. No issues thus far.

**Pull request merged**
