### PR TITLE
[DONOTMERGE] tama: Add initial support

### PR DESCRIPTION
**Pull request by oshmoun**

### CODE REVIEW

**Comment by jerpelea** [comment]
@oshmoun 
12-10 16:35:09.303   871   871 D FPC IMP : Setting GID to 0
12-10 16:35:09.323   871   871 D FPC IMP : Loading user db from /data/system/users/0/fpdata/user.db
12-10 16:35:09.333   871   871 I FPC IMP : Found 0 fingerprints
12-10 16:35:42.035   871   871 I AOSP FPC HAL (Binder): preEnroll : Challenge is : 12134207103843688201
12-10 16:35:50.278   871   871 I AOSP FPC HAL (Binder): enroll : hat->challenge 12134207103843688201
12-10 16:35:50.278   871   871 I AOSP FPC HAL (Binder): enroll : hat->user_id 8065684933796071427
12-10 16:35:50.278   871   871 I AOSP FPC HAL (Binder): enroll : hat->authenticator_id 0
12-10 16:35:50.278   871   871 I AOSP FPC HAL (Binder): enroll : hat->authenticator_type 16777216
12-10 16:35:50.278   871   871 I AOSP FPC HAL (Binder): enroll : hat->timestamp 9409991045925568512
12-10 16:35:50.278   871   871 I AOSP FPC HAL (Binder): enroll : hat size 69
12-10 16:35:50.282   871   871 I FPC IMP : verify auth challenge: 0
12-10 16:35:50.282   871   871 D AOSP FPC HAL (Binder): setState : Setting state to = 1
12-10 16:35:50.282   871   971 I AOSP FPC HAL (Binder): worker_thread : ENROLL
12-10 16:36:50.746   871   871 I AOSP FPC HAL (Binder): cancel
12-10 16:36:50.746   871   871 D AOSP FPC HAL (Binder): setState : Setting state to = 4
12-10 16:36:50.747   871   871 I AOSP FPC HAL (Binder): cancel : Successfully moved to cancel state
12-10 16:36:50.747   871   971 D FPC COMMON: Waking up from eventfd
12-10 16:36:50.747   871   971 D AOSP FPC HAL (Binder): process_enroll : Got Input status=1001
12-10 16:36:50.747   871   971 I AOSP FPC HAL (Binder): isCanceled : Operation canceled
12-10 16:37:06.671   871   871 I AOSP FPC HAL (Binder): enroll : hat->challenge 12134207103843688201
12-10 16:37:06.671   871   871 I AOSP FPC HAL (Binder): enroll : hat->user_id 8065684933796071427
12-10 16:37:06.671   871   871 I AOSP FPC HAL (Binder): enroll : hat->authenticator_id 0
12-10 16:37:06.671   871   871 I AOSP FPC HAL (Binder): enroll : hat->authenticator_type 16777216
12-10 16:37:06.671   871   871 I AOSP FPC HAL (Binder): enroll : hat->timestamp 9409991045925568512
12-10 16:37:06.671   871   871 I AOSP FPC HAL (Binder): enroll : hat size 69
12-10 16:37:06.675   871   871 I FPC IMP : verify auth challenge: 0
12-10 16:37:06.675   871   871 D AOSP FPC HAL (Binder): setState : Setting state to = 1
12-10 16:37:06.676   871   971 I AOSP FPC HAL (Binder): worker_thread : ENROLL

**Comment by MarijnS95** [comment]
@jerpelea What's the problem? This log looks identical to what I see on Suzu when manually cancelling the enroll.

**Comment by jerpelea** [comment]
no finger detected

**Comment by oshmoun** [comment]
it works here, an enrolled finger is recognized upon authentication (can unlock device with fpc)
however, there are a couple issues:
1. when enrolling, one can hold a finger on the sensor and it will take successive scans, not waiting to lose the finger
2. a crash  happens when trying to delete an enrolled fingerprint https://pastebin.com/jzhixG2k
3. when in fingerprint settings, and an unrecognized finger is tried multiple times, fpc enters an unexpected state https://pastebin.com/vpz4qFwy

**Comment by jerpelea** [comment]
I tested the commit and functionality is ok with the mentioned bugs

**Pull request merged**
